# Generated by Django 3.0.3 on 2020-02-19 21:26

import cms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_text',
        ),
        migrations.AddField(
            model_name='section',
            name='href',
            field=cms.models.VarCharField(blank=True, verbose_name='link'),
        ),
    ]
