# Generated by Django 3.0.2 on 2020-03-21 17:13

import cms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200219_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ButtonSection',
        ),
        migrations.DeleteModel(
            name='ContactSection',
        ),
        migrations.DeleteModel(
            name='ImageSection',
        ),
        migrations.DeleteModel(
            name='TextSection',
        ),
        migrations.DeleteModel(
            name='VideoSection',
        ),
        migrations.RemoveField(
            model_name='section',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=cms.models.VarCharField(verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=cms.models.VarCharField(verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=cms.models.VarCharField(verbose_name='type'),
        ),
    ]
